### ISSUE TITLE
Snapshot counts ignore supplied filters

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#103]
**Describe the bug**
Today, if the user applies filters on the Overview page, their snapshot totals won't change based on the filters, while the rest of the UI does change. In the past this was done on purpose, but we've re-evaluated it in light of the newer visualizations we've introduced to the Uptime UI.

**To Reproduce**
1. Set up Kibana with some Heartbeat monitors
2. Apply some Overview page filters
3. Observe that the snapshot counts did not change

**Expected behavior**
When applying filters the total counts would update

**Debug logs**
N/A

**Example**:
_Before filters_
![image](https://user-images.githubusercontent.com/18429259/67573272-f17e6380-f705-11e9-87f6-ebfc734f1264.png)

_After filters_
![image](https://user-images.githubusercontent.com/18429259/67575240-183e9900-f70a-11e9-8663-79c5f56a9cc9.png)

**Comment by andrewvc** [comment]
I dove into this.The query backing the counts is wrong. It should really use the monitor states query. As is it usually gives the right answer, but doesn't do status filtering right.

We should refactor this to use the monitor states query, but since GQL types are broken we're blocked on refactoring to REST/io-ts first.

While we can 'fix' this proximate issue without that, I think testing it makes more sense with the correct query anyway.

**Comment by justinkambic** [comment]
@andrewvc check out the backend code for https://github.com/elastic/kibana/pull/48035, I believe it will fix this, as well as getting this component off of GQL and onto REST/`io-ts`

**Comment by andrewvc** [comment]
This issue is being tracked by https://github.com/elastic/kibana/issues/47376 , so we can close this one.
