### ISSUE TITLE
[Uptime UI] duration anomaly detection

### ISSUE THREAD

**Issue by katrin-freihofner** [elastic/uptime#155]
**Summary of the problem** (If there are multiple problems or use cases, prioritize them)
With ML in place, we can show anomalies in duration. 

Questions to solve:
- How can users set up anomaly detection?
- How do we indicate anomalies in the duration chart?
- How can users investigate anomalies?

**Comment by katrin-freihofner** [comment]
[Figma prototype](https://www.figma.com/proto/lDlGXMzUTnzAlHPQu7lZAH/Uptime?node-id=69%3A5&viewport=-5012%2C1550%2C0.5&scaling=min-zoom)

**Comment by katrin-freihofner** [comment]
This video shows the basic user flow to enable anomaly detection:

![uptime-ml](https://user-images.githubusercontent.com/20965076/76305238-12b2ab80-62c5-11ea-8f81-ac1efa7f39b9.gif)

## Changes in detail

### Overview page
If anomaly detection is enabled, an additional column in the monitor table shows the anomaly score.
<img width="1368" alt="Screenshot 2020-03-10 at 16 57 01" src="https://user-images.githubusercontent.com/20965076/76332043-2f180d80-62f0-11ea-8ba8-87b5e2eaa2f7.png">



### Details page

- A primary button next to the duration chart should enable the anomaly detection -> triggers the flyout
- Once enabled, the button next to the duration chart turns into an Eui empty button to disable the anomaly detection.
- Once ML is enabled the duration chart legend shows the anomaly scores (critical anomaly >= 75, major anomaly >= 50)
- The anomaly annotations in the chart are visible
- on hover of the chart, the information about the anomalies is shown (only critical and major anomaly scores)
<img width="694" alt="Screenshot 2020-03-10 at 16 58 46" src="https://user-images.githubusercontent.com/20965076/76332273-73a3a900-62f0-11ea-996a-65507de2f6a7.png">

<img width="544" alt="Screenshot 2020-03-10 at 16 54 21" src="https://user-images.githubusercontent.com/20965076/76331869-f4ae7080-62ef-11ea-9cfa-76b0d82ad660.png">



If we have too little training data, a warning callout is shown.
<img width="691" alt="Screenshot 2020-03-10 at 11 55 36" src="https://user-images.githubusercontent.com/20965076/76306312-f4e64600-62c6-11ea-9bb9-f973a4de0a50.png">

**Comment by drewpost** [comment]
The way this should be done is, upon the creation of the ML job, to look at the frequency of the monitor and automatically create a window that includes enough data points with a minimum duration threshold to prevent too much noise. So, we check every minute, the last 15 minutes worth of data UNLESS the monitor has a frequency of 5minutes or more in which case we will expand the interval to include at least 15 data points. 

In that situation, the only time this message above would appear is if the monitor itself is too new to have enough data. In which case: "This monitor has been recently created. Anomaly detection will begin in the next 1-2 hours, once there enough results to enable accurate analysis"

**Comment by andrewvc** [comment]
After discussing the current design/flow we will make the following changes:

1. No enable button at the top of the page
2. "Enable Anomaly Detection" button will take the place of the "Explore in ML" button on the chart
3. Clicking the button to enable will check to see if the `observer.geo.name` field is present. If it is a multi-metric job will be created, if not a single metric job will be created.
4. After clicking this, instead of a flyout, a toast (that requires manual dismissal) will be created, saying: "Your Machine Learning job has been created. We noticed you aren't setting [geographic location](https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-observer-options.html) in heartbeat. If you later add this data you'll need to disable and re-enable anomaly detection to see data by location"
