### ISSUE TITLE
Add timestamp value tooltip on hover in Ping List

### ISSUE THREAD

**Issue by justinkambic** [elastic/uptime#174]
**Is your feature request related to a problem? Please describe.**
Today, the Monitor List's relative timestamp copy (i.e. `2m ago`) provides a tooltip with the absolute time value `onHover`, like below:

![image](https://user-images.githubusercontent.com/18429259/79883086-7bf80500-83c1-11ea-958f-6cad3a9d2c70.png)

I think the Ping List on the Monitor Detail page should implement this as well:
![image](https://user-images.githubusercontent.com/18429259/79883169-94681f80-83c1-11ea-805b-df71702a41ae.png)

**Describe the solution you'd like**
We'd simply follow the same conventions employed by the Monitor List to add this functionality.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by andrewvc** [comment]
I like this idea. Looking at how it works today, I think the relative timestamps are functionally broken. In the SS provided everything looks like it was checked at the same time even though that clearly is not the case.

I'm actually wondering if it makes more sense to report an absolute timestamp instead of the relative one always. We could also add a state to the page when we detect stale data and say "Haven't received checks from heartbeat, it seems to have missed its last expected check by X seconds".

Thoughts @drewpost @katrin-freihofner ?

**Comment by katrin-freihofner** [comment]
- I think the tooltip is a great idea.

- To me, the absolute timestamp is harder to read that is why I would leave the relative one in the table as we have it right now.

**Comment by justinkambic** [comment]
> To me, the absolute timestamp is harder to read

I find the same thing for the absolute values we show on the certs page today as well. It can be hard to know when an event happened relative to now when looking at absolute dates.

**Comment by paulb-elastic** [comment]
We are now showing absolute times for these, so this is no longer needed.
