### ISSUE TITLE
[Exploratory View] Add to Case

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#322]
As a user of the Observability cases capability
I want to be able to add a visualisation I've created in the exploratory view to an existing case
So that I can communicate observed insight visually in a way that users can then come back and manipulate themselves

ACs:

- There is an "add to case" option in exploratory view
- The case option shows all open cases
- There is a search box to filter the list down based on case name or identifier
- Adding a chart to a case is a snapshot in time. It will add the chart, as currently displayed, to the specified case. 
-- If a chart is using relative date ranges, these are converted to absolute date ranges
- If an exploratory view chart is modified, and added to a case again, it does not replace what is already there but rather adds a new copy of the current state
- There should be a link from cases back into exploratory view that loads the given chart in exploratory view(moved to a new issue https://github.com/elastic/uptime/issues/367)

**Comment by katrin-freihofner** [comment]
There is already a "add to new/existing case" workflow for alerts, we might be able to reuse.

**Comment by paulb-elastic** [comment]
@liciavale (cc @drewpost), we might need some help working out the best design for this (see also Katrin's comment above).

**Comment by shahzad31** [comment]
@drewpost Observability cases are still behind feature flag, does that effect this ticket?

**Comment by drewpost** [comment]
@shahzad31 My understanding is that they will be out from there in 7.16. @cyrille-leclerc can you confirm if that is still on track?

**Comment by katrin-freihofner** [comment]
This is the workflow we currently have in place in the alerts view:

## Creating a new case
<img width="1378" alt="Screenshot 2021-09-16 at 13 54 05" src="https://user-images.githubusercontent.com/20965076/133607663-bdaed977-31a8-4438-b1b2-f355a98f5408.png">

## Adding alert to an existing case
<img width="1378" alt="Screenshot 2021-09-16 at 13 53 54" src="https://user-images.githubusercontent.com/20965076/133607670-9528175e-ba40-4603-bd8e-2edb18f5bdf6.png">

You can test the interaction on edge.

**Comment by lucasfcosta** [comment]
I've tested this PR in two ways: [following Dominique's comments on the PR](https://github.com/elastic/kibana/pull/112463#pullrequestreview-764358413), and following Paul's instructions in this issue.

# Test Results (As per Paul's description)

As per Paul's description, here's how I've tested this issue:

1. I created five cases:
    1. two open cases from different reporters each
    2. one in-progress case
    3. one closed case
    4. one reopened case


![Screenshot 2021-11-01 at 16 57 57](https://user-images.githubusercontent.com/6868147/139710115-6f919202-7a8f-44be-8abf-394e3dc2a3b5.png)

2. I created a new visualisation using the Exploratory View and added it to an open case.
3. I could correctly filter cases by their statuses, names, reporters, and tags.
5. The toast informing that the visualisation was added successfully is displayed as expected, and its link works.
6. I went into the case and was able to find the visualisation in there, as expected.

![saving-to-case-and-filters](https://user-images.githubusercontent.com/6868147/139710758-32808cde-9909-4391-8894-a3272bea771f.gif)

7. When editing a visualisation and removing a metric from it, the visualisation within the case did not change, as expected.

![editing-preserves-case](https://user-images.githubusercontent.com/6868147/139711026-276a6f8c-812c-4943-9d88-d3b3d222aa5e.gif)

8. When adding a visualisation with relative dates, those were _not_ converted to absolute dates. As you can see in the GIF below, every time I refreshed the case, I was able to see more recent measurements because the end date was set as "now".
    Additionally, the `start_date` also changes so that it's always X minutes ago, not at an absolute time.
    Clicking "open visualisation" also displays the relative time as the chart's time range.
    ![relative-not-working](https://user-images.githubusercontent.com/6868147/139713424-94ef997a-e490-4c87-bdb1-0d088c0df944.gif)
    The related issue for this is at: https://github.com/elastic/kibana/issues/117008

2. This issues lists as an acceptance criteria:
     > The case option shows all open cases
     However, the case options show _all_ cases, including closed ones. It's also possible to add a visualisation to a closed case. In my opinion, that seems okay from a functional perspective, but given it deviates from the original spec I've added an issue here: https://github.com/elastic/kibana/issues/117006. Please feel free to close if the spec has changed or if we're actually okay with it as is.
     
![adding-to-closed-case](https://user-images.githubusercontent.com/6868147/139714404-94b464a9-06bb-4c92-afd9-15a4925b8ec8.gif)

# Test Results ([as per Dominique's comments on the PR](https://github.com/elastic/kibana/pull/112463#pullrequestreview-764358413))

## Test Case 1 - "Add To Case" modal button should work after changing report type

1. Clicked "Add To Case" > Closed the "Add To Case" modal
2. Changed report type
3. Clicked "Add to Case" button again, and it works as expected.

![readd-change-type-works](https://user-images.githubusercontent.com/6868147/139715733-c5234970-8923-47f4-bce2-eb399feb39dd.gif)

## Test Case 2 - "Add To Case" modal button should work after changing report type

1. Using Synthetics Monitoring -> KPI Over Time as an example, set a value for monitor name
2. Click Add To Case Button
3. Exit Add To Case modal
4. Remove monitor name
5. Add monitor name again
6. Notice that the modal _does not_ pop up again without clicking the button.

![changing-name-no-popup](https://user-images.githubusercontent.com/6868147/139716367-fc63f4d2-9e84-4662-8a5d-20ec0d1a5796.gif)


-------------

# Questions

1. When selecting tags, as the popup changed dimensions, the position of the `select` element ended up being a bit weird. Is that an issue I should report on Kibana or in our component library?
2. Can someone confirm the "Expected Behaviour" I described in https://github.com/elastic/kibana/issues/117006 is really the desired one? (CC @drewpost and @paulb-elastic).

**Comment by shahzad31** [comment]
@lucasfcosta 

Thanks for the detailed testing
Regarding
`When selecting tags, as the popup changed dimensions, the position of the select element ended up being a bit weird. Is that an issue I should report on Kibana or in our component library?
`

Please open an issue in the kibana repo, we will redirect it to the team which owns this component, i think it's woned by RAC initiative. 

And thanks for opening the other issue regarding https://github.com/elastic/kibana/issues/117006

we can probably discuss this in refinement as well.
