### ISSUE TITLE
Move existing APIs to async search - Certificates page

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#354]
We should migrate our existing APIs to async search to enable support for searchable snapshot as described in https://github.com/elastic/uptime/issues/293

**Comment by dominiqueclarke** [comment]
Post FF testing

Kibana branch 7.16

Certificates page LGTM.

<img width="1518" alt="Screen Shot 2021-10-21 at 4 04 06 PM" src="https://user-images.githubusercontent.com/11356435/138349539-13308cd4-edec-4d7e-8bc7-8c9a199d63c6.png">

Also did regression on TLS alerts, since the PR made some adjustments to that as well. That also LGTM.
