### ISSUE TITLE
Make Agent Flow the Primary Flow in Uptime for 7.16

### ISSUE THREAD

**Issue by drewpost** [elastic/uptime#366]
We are going to move to Integrations and Agent based monitor management as our primary workflow from 7.16 onwards. We also want to make the script recorder beta open for all users to optionally use and provide feedback on. To achieve this, we need to make the following changes:

- [ ] ~~Change the tile on "Home > Add Data" to match that in the Integration (title and description)~~
- [ ] ~~Change the add data page from /app/home#/tutorial/uptimeMonitors to /app/integrations/detail/synthetics-0.3.0/overview~~
  - [x] ~~As accessed from the "No data" state~~
  - [ ] ~~As accessed from the "Home > Add Data" tile~~
  - [x] ~~As accessed from the "Add data" link on Uptime~~
- [x] elastic/uptime#371
- [x] Default is to the Zip file tab in the integration for browser monitors
- [x] Synthetics Recorder Beta repo is opened up to the public
- [x] Recorder beta has some documentation and a helping content created https://github.com/elastic/observability-docs/issues/988
- [ ] ~~Change the badge to remove beta~~

**Comment by shahzad31** [comment]
We also need to update tha Add data button link as well, right?

**Comment by paulb-elastic** [comment]
Discussed with @drewpost  and because of a change in approach for the integrations, we want to keep the flow as it is (i.e. the same in 7.16 as it is in 7.15), in terms of how users are directed to add data (and not change the default to be Agent and the Synthetics Integration) in 7.16.  Also, we will need to keep the `beta` label on the existing Synthetics Integration in 7.16.

The changes to support the script recorder (add option/link for the script recorder, open up the repo, some docs) are to remain, as we would still like users to start using the tech preview version of the script recorder in 7.16 (users that find it, and users we direct to it - there won’t be a big announcement about it yet).

I’ve added strikethroughs to items in the description that are no longer needed (some of which will unfortunately need to be reverted/re-implemented).

/cc @dominiqueclarke @elastic/uptime

**Comment by paulb-elastic** [comment]
@vigneshshanmugam, the last remaining activity here is to open up the script recorder repo.  Do you want to do this now or wait until 7.16 is released?  Is there any reason to wait?

**Comment by paulb-elastic** [comment]
Repo public, last remaining item, closing.
