### ISSUE TITLE
[Uptime] Show inline errors on Monitor Management

### ISSUE THREAD

**Issue by paulb-elastic** [elastic/uptime#439]
This is the `inline` error version of those we'll be adding for `suites` in https://github.com/elastic/uptime/issues/438.

This depends on https://github.com/elastic/beats/issues/29897.

As a Synthetics Service User
I want to clearly see if my inline script has a problems (syntax error) that is preventing the monitor from running
So that I quickly debug the issue to a resolution and get the monitor working

ACs:
* The Monitor Management page should show any inline script errors
  * These should reflect the same errors as shown in the main Uptime Monitors page, and also use a similar UX as implemented in https://github.com/elastic/uptime/issues/435

Example layout adding to the main Monitor Management table:
![image](https://user-images.githubusercontent.com/70908889/149804793-089d02f9-aa35-4fa2-b98d-05ef629ea5fb.png)

**Comment by shahzad31** [comment]
@paulb-elastic @drewpost i am bit confused what's the scope of errors here. 
Do we display errors when journey can't even start, or any error will appear here?

**Comment by drewpost** [comment]
I think the wording is confusing. This page is meant to only show an error if it's related to monitor config (in this case a syntax error in an inline script). It does NOT show the status of test runs.

The confusing part is mentioning showing the same errors as on the overview page. What this means is that if a monitor is unable to run because of an error, we want to tell users of that on the overview page too. We want that status to be consistent between the two pages.

Is that a correct understanding @paulb-elastic ?

**Comment by paulb-elastic** [comment]
Apologies for any confusion.  Correct @drewpost, this is to show users when there is a problem with the monitor configuration (script code), which means it cannot run (i.e. we are unable to determine if the site under test is UP or DOWN).  It is **not** meant to reflect the status of the monitor (UP or DOWN).

The reference to _…the same errors as on the overview page_ which may have caused confusion, was referring to the way (UX) we are displaying these on the other page:
![image](https://user-images.githubusercontent.com/70908889/152520147-15a3780f-d30c-4157-99c4-dda01084b2d3.png)

Does that help clear it up?
