### ISSUE TITLE
Private monitor management locations MVP

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#475]
This takes over for https://github.com/elastic/uptime/issues/441 which has grown long and unwieldy.

This issue defines ACs for an initial implementation of private locations for monitor management in the Uptime app. The locations are
to be implemented atop fleet continuing the work in @shahzad31 's POC

### Design

![image](https://user-images.githubusercontent.com/847805/178748965-480f7e61-64fe-40f3-a51d-a27f107b4f77.png)

## Flyout

Flyout is 540px wide.

**When private locations exist**
![image](https://user-images.githubusercontent.com/847805/180297127-207a197e-e3d5-4048-9d06-d9ac42476d0d.png)

**When no locations exist**
![image](https://user-images.githubusercontent.com/847805/180297173-fb574746-6b3d-4b24-8bfd-835b404549f3.png)

**Add location form**
![image](https://user-images.githubusercontent.com/847805/180297267-6c4cda5f-9357-4d3e-8645-e1230523fd78.png)

**Condition when no agent policies exist**
![image](https://user-images.githubusercontent.com/847805/180297287-2b89f60c-24db-4c00-b635-ed51c19c86eb.png)

### Uptime
- [x] Update monitor management to be accessible to all users, including self managed. (We still have to see if the service will require filling out the google form)
- [x] Public locations will only be visible to customers who can use them (ESS users)
- [x] Ensure `your data will leave this stack` text is still clearly visible in monitor management
- [x] Run once and test now functionality will be disabled for monitors that only have a private location assigned. (Either hide the component, or gray out with tooltip explaining reason)

## Monitor Management
- [x] Remove concurrency control for now
- [x] Include lat / lon (as separate fields to reduce formatting issues). Should be optional
- [x] Private locations appear in list alongside regular locations with label indicating private status 
- [x] If no private locations exist and the user is not on ESS (they have a empty location list) a message will be displayed asking the user to create a private location
- [x] User should have to click accept the following terms:

```
By using this feature, Customer acknowledges that it has read and agrees to Elastic's Beta Release Terms https://www.elastic.co/agreements/beta-release-terms 

There is no cost for the use of the service to execute your tests during the beta period. A fair usage policy will apply. Normal data storage costs apply for test results stored in your Elastic cluster.
```

This should be added to the following screen, below the existing text

![mm-stage2](https://user-images.githubusercontent.com/131427/178741760-08e103d7-7af1-4d12-a61d-194390be15c3.png)

### Fleet UI
- [x] Integrations created by monitor management will not be editable
- [x] Messaging will be present directing users to monitor management when not editable.

**Comment by dominiqueclarke** [comment]
For users entering through the Elastic Synthetics page, should we disable the ability to add integrations directly and navigate them to MM? 

> Run once functionality will be disabled for monitors that only have a private location assigned. (Either hide the component, or gray out with tooltip explaining reason)

Test now functionality should also be disabled.

**Comment by hbharding** [comment]
## Update

I added some designs for the Private location flyout to the issue description based on a session with @shahzad31 and @dominiqueclarke. I made these pretty quickly based on Shahzad's work. I'm hoping these are relatively small improvements we can get in, but I certainly don't want to block this feature from getting into the next release. Let me know if there are any areas we can simplify.

## Other feedback

---

![image](https://user-images.githubusercontent.com/847805/180299720-bc162b46-d805-4043-8b70-63d2a4de48af.png)

Remove the map marker icon and just say "Private locations".

---

![image](https://user-images.githubusercontent.com/847805/180300059-90da74bb-516f-4dae-a755-ffc352fceb3b.png)

Change text to "This policy is managed externally", or even better / if possible, "This policy can be managed in the Uptime application". Also, use the tooltips `content` prop rather than the `title` prop

---

![image](https://user-images.githubusercontent.com/847805/180300370-525c7d12-25b9-4a45-806a-2cdea1b24c93.png)

I understand we can only control the bottom portion of this page, but as is, this is pretty confusing and it feels like there is a lot of unnecessary content on the page. If possible, can we use a single callout with a link to Uptime, and not show any of the form inputs since they are not editable?

**Comment by dominiqueclarke** [comment]
Setup
---
Testing this feature requires Fleet server and `elastic-agent-complete` running in Docker. 

You can choose to either set up Fleet server and elastic-agent manually or automated using `elastic-package`. Both methods require a bit of investment upfront to set up.

Via `elastic-package`
---
1. Run `elastic-package stack up --version 8.4.0-SNAPSHOT -v`
2. Once the stack is up, stop kibana using docker desktop management
3. Add the following to your local `kibana.dev.yml`
```
elasticsearch:
  hosts: ["https://localhost:9200"]
  username: "kibana_system"
  password: "changeme"
xpack.fleet.registryUrl: https://localhost:8080
```
4. Run `curl -k -u elastic:changeme -X POST "https://localhost:9200/_security/user/kibana_system/_password?pretty" -H 'Content-Type: application/json' -d' { "password" : "changeme" } '`
5. Run `eval "$(elastic-package stack shellinit)"`
6. Run `export NODE_EXTRA_CA_CERTS=${ELASTIC_PACKAGE_CA_CERT}`.
7. Start your local Kibana. Fleet server and agent should now be configured correctly. You can confirm by visiting the fleet page

Via manual setup
---
1. In Kibana, navigate to the Fleet page and follow the directions to add Fleet server
2. Create a new agent policy from fleet
3. Under the enrollment tab, generate a new enrollment token for the new policy you created
4. Enroll elastic-agent in that policy. Run `docker run --env FLEET_ENROLL=1 --env FLEET_INSECURE=1 --env FLEET_ENROLLMENT_TOKEN=<TOKEN> --env FLEET_URL=<URL> docker.elastic.co/beats/elastic-agent-complete:8.4.0-SNAPSHOT -d "*" -e`

Testing
---
Note: All testing should be done on the 8.4 branch of Kibana, or, where appropriate, against an 8.4.0-SNAPSHOT in cloud first test

This feature has diverging UX depending on the user's permissions. To test all code paths, you will need two users with two different roles. Below are the required users and associated permissions. Create two users with the following permissions:

Fleet user
|   |   |   | 
|---|---|---|
| Kibana permission |  Fleet | all |  
| Kibana permission  |  Integrations | all |  
| Kibana permissions |  Uptime | all  |
| Cluster permission | manage_own_api_keys |
| Index permission | synthetics-* | all |

Uptime user
|   |   |   | 
|---|---|---|
| Kibana permissions |  Uptime | all  |
| Cluster permission | manage_own_api_keys |
| Index permission | synthetics-* | all |

Fleet user - Cloud
---

Setup:
1. Add the following keys to Kibana.yml. This will cause Kibana to run under a cloud context: https://p.elstc.co/paste/4evUZg9W#RQNLl3iVTsPUVpfPlhH8U4CWM007ONUcgIr+VXWm9Aa

|   |   |   | |
|---|---|---| --- |
| When |  I first visit Monitor Management | I see an enabled prompt with legal text implying that my use means acceptance of T&C  |
| When |  I first enable Monitor Management | I see an empty monitor list, the Add Monitor button is enabled, and the Private Locations button is Visible |
| When | I click on the Private Locations button | A flyout appears with a prompt to add my first location |
| When | I click add location | if I have existing agent policies | I am prompted to add the location name and select an agent
| When | I click add location | if I don't have existing agent policies | I see a prompt directing me to add an agent by redirecting to Fleet |
| When | I add a location | It's added to the locations list | I cannot edit it
| When | I click Add monitor | I see the newly added location in the locations list | It has a `Private` label
| When | I have a monitor configured for a private location | I cannot delete that private location until all monitors for that location are removed
| When | I have no monitors for a given location | I can delete that private location
| When | I save a monitor with a private location | The data should appear in Uptime overview list, and the location for the check should be marked with the correct location name
| When | I visit the associated Agent Policy page in Fleet for a given location | Any integrations made from private locations are not able to be deleted
| When | I visit the associated Agent Policy page in Fleet for a given location | When I click edit integration | I'm redirected to a read-only view where I can navigate to monitor management. 
| When | I create monitors with the same name in different spaces | I do not get any errors
| When | I delete an agent policy tied to a private location | My private location displays as invalid | I can edit existing monitors to remove the invalid location 

Uptime only user - Cloud
---
Setup:
1. Add the following keys to Kibana.yml. This will cause Kibana to run under a cloud context: https://p.elstc.co/paste/4evUZg9W#RQNLl3iVTsPUVpfPlhH8U4CWM007ONUcgIr+VXWm9Aa

Prerequisites
* Ensure monitor management is already enabled by the admin user

|   |   |   | |
|---|---|---| --- |
| When | I click on the Private Locations button | A permissions disclaimer is displayed | I cannot add or delete private locations
| When | I click Add monitor | I see public and private locations | Private locations are disabled
| When | I visit the monitor list| the edit and delete buttons are disabled for monitors with private locations | the edit and delete buttons are enabled for monitors with public locations |
| When | I click the api key button | I see a prompt notifying me that my permissions are insufficient to use private locations | I can still create an api key


Fleet user - On Prem
---

Setup
1. REMOVE the following keys to Kibana.yml. This will cause Kibana to run under an on-prem context. Ensure no other `x-pack.uptime.service` keys are defined https://p.elstc.co/paste/4evUZg9W#RQNLl3iVTsPUVpfPlhH8U4CWM007ONUcgIr+VXWm9Aa

|   |   |   | |
|---|---|---| --- |
| When |  I first visit Monitor Management | I see an enabled prompt with legal text implying that my use means accepted of T&C  |
| When |  I first enable Monitor Management | I see a prompt directing me to create my first location |
| When | I don't have any private locations | The add monitor button is disabled |
| When | I click on the Private Locations button | A flyout appears with a prompt to add my first location |
| When | I click add location | if I have existing agent policies | I am prompted to add the location name and select an agent
| When | I click add location | if I don't have existing agent policies | I see a prompt directing me to add an agent by redirecting to Fleet |
| When | I add a location | It's added to the locations list | I cannot edit it
| When | I click Add monitor | I see the newly added location in the locations list | It has a `Private` label
| When | I have a monitor configured for a private location | I cannot delete that private location until all monitors for that location are removed
| When | I have no monitors for a given location | I can delete that private location
| When | I save a monitor with a private location | The data should appear in Uptime overview list, and the location for the check should be marked with the correct location name
| When | I visit the associated Agent Policy page in Fleet for a given location | Any integrations made from private locations are not able to be deleted
| When | I visit the associated Agent Policy page in Fleet for a given location | When I click edit integration | I'm redirected to a read-only view where I can navigate to monitor management. 
| When | I create monitors with the same name in different spaces | I do not get any errors
| When | I delete an agent policy tied to a private location | My private location displays as invalid | I can edit existing monitors to remove the invalid location 

Uptime only user - On Prem
---
Setup
Setup
1. REMOVE the following keys to Kibana.yml. This will cause Kibana to run under an on-prem context. Ensure no other `x-pack.uptime.service` keys are defined https://p.elstc.co/paste/4evUZg9W#RQNLl3iVTsPUVpfPlhH8U4CWM007ONUcgIr+VXWm9Aa

Prerequisites
* Ensure monitor management is already enabled by the admin user

|   |   |   | |
|---|---|---| --- |
| When | I click on the Private Locations button | A permissions disclaimer is displayed | I cannot add or delete private locations
| When | I visit the monitor list | the Add Monitor Button is Disabled |
| When | I visit the monitor list | the edit and delete buttons are disabled |
| When | I click the api key button | I see a prompt notifying me that my permissions are insufficient to use private locations | I can still create an api key


Fleet user - Project Monitors
---
Setup
1. In Kibana, sign into the Fleet user and generate an api key from the API Keys button. Note: (In order to use private locations, you must generate the api key from a user with Fleet permissions, so ensure you create a new api key instead of using an old one)
5. In Kibana, ensure you have private locations configured by clicking the Private Locations button and adding a location
6. Check out the main branch of the `synthetics` repo.
11. Run npm run build
12. cd `./examples/todos`.

Example command (You can assign private locations by the location's name)
```
node ../../dist/cli.js push  --url [YOUR_KIBANA_URL] --project test-project --auth [YOUR_API_KEY] --schedule 3 --privateLocations "[YOUR LOCATION NAME]"
```
Example dsl (You can assign private locations by the location's name)
```
journey('check if input placeholder is correct', ({ page, params }) => {
  monitor.use({
    schedule: 5,
    privateLocations: ["YOUR LOCATION NAME"]
  })
  step('launch app', async () => {
    await page.goto(params.url);
  });
});
```
In Kibana
|   |   |   | |
|---|---|---| --- |
| When | I click on the API key button in Kibana | I can create an API key with Uptime and Fleet permissions

From the command line
|   |   |   | |
|---|---|---| --- |
| When | I define a default private location via --privateLocations and do not define `privateLocations` via `monitor.use` | The monitor is created with that location
| When | I define a private location via `monitor.use({ privateLocations: [...] })` | The monitor is created with that location
| When | I update a monitor that has an assigned private location | The monitor is updated | The associated integration policy is updated
| When | I delete a location by removing it from `monitor.use`  re-push| The monitor is updated to remove that location | The associated Integration policy is deleted
| When | I delete a monitor and re-push | The monitor | The associated Integration policy is deleted

Uptime user - Project Monitors
---
Setup
1. In Kibana, sign into the Uptime user and generate an api key from the API Keys button. Note: (This api key will have limited permissions, causing errors)
4. In Kibana, ensure you have private locations configured by clicking the Private Locations button and adding a location
5. Check out the main branch of the `synthetics` repo.
7. Run npm run build
8. cd `./examples/todos`.

Example command (You can assign private locations by the location's name)
```
node ../../dist/cli.js push  --url [YOUR_KIBANA_URL] --project test-project --auth [YOUR_API_KEY] --schedule 3 --privateLocations "[YOUR LOCATION NAME]"
```
Example dsl (You can assign private locations by the location's name)
```
journey('check if input placeholder is correct', ({ page, params }) => {
  monitor.use({
    schedule: 5,
    privateLocations: ["YOUR LOCATION NAME"]
  })
  step('launch app', async () => {
    await page.goto(params.url);
  });
});
```
In Kibana
|   |   |   | |
|---|---|---| --- |
| When | I click on the API key button in Kibana | I see a disclaimer stating that I cannot use private locations | I can still create an api key

From the command line
|   |   |   | |
|---|---|---| --- |
| When | I define a default private location via --privateLocations and do not define `privateLocations` via `monitor.use` and push | I receive an error stating that I do not have permissions
| When | I define a private location via `monitor.use({ privateLocations: [...] })` and push | I receive an error stating that I do not have permissions
| When | I attempt to update a monitor that has an assigned private location | I receive an error stating that I do not have permissions
| When | I delete a location by removing it from `monitor.use`  re-push | I receive an error stating that I do not have permissions
| When | I delete a monitor and re-push | I receive an error stating that I do not have permissions

**Comment by lucasfcosta** [comment]
It took me quite a bit of time to set things up due to https://github.com/elastic/synthetics-service/issues/685. So I had to fix that locally before proceeding. Also, setting up a remote OBLT cluster was not possible because of the `SNAPSHOT` version there.

I ended up testing this locally against the elastic stack with the change which allows the service to disable SSL on dev mode.

Will post feedback for the other flows in a bit.

(click to links to see images)

# Fleet user

1. Created the role and user
  ([Role](https://user-images.githubusercontent.com/6868147/181253638-decae358-96eb-446e-a18f-94b082904699.png), [Role](https://user-images.githubusercontent.com/6868147/181253648-b18c4fe0-2c50-4e9d-889e-2bb86b1400c1.png), [User](https://user-images.githubusercontent.com/6868147/181253643-f4598c6a-559c-4d18-b9d6-2e5863d761b0.png))
2. First visit displays the correct page with links to docs and ToS
  ([TOS](https://user-images.githubusercontent.com/6868147/181253924-b478577c-a124-45bd-8ced-517c3808ec82.png))
3. Enabling Monitor Management as an admin shows the list with the add button enabled for the Fleet user
    ([Enabled Button and List](https://user-images.githubusercontent.com/6868147/181254083-a9e178bd-8c61-4dbb-9d90-3fd35825b7d4.png)
4. I can run the monitors I create and save them.
  ([Running monitors](https://user-images.githubusercontent.com/6868147/181261243-0d676d10-9c7f-4688-9aff-a582fc52f63e.png))
5. I can open the flyout to create a private location and buttons are enabled.
  ([Private Locations Flyout](https://user-images.githubusercontent.com/6868147/181261441-f4efb99e-1477-4c99-a202-f542f337d11e.png))
6. Once I have a policy, I cannot add the private location.
  **When clicking `save`, nothing happens.**
   There are no error logs in Kibana backend.
  ([Flyout Overview](https://user-images.githubusercontent.com/6868147/181276637-73715072-0271-4ff2-98f5-9ff7739f2bff.png))
7. After some debugging I discovered it's because of the `beta` value for the dev manifest location. It needs to be `ga` or `experimental` instead. To solve it I used my own local manifest.

    Please notice that the same problem happens if Kibana can't fetch locations.
  
    ([Error related to location being `beta`](https://user-images.githubusercontent.com/6868147/181277258-6e006610-7165-47af-a4fa-0fb53d8eb8ec.png))

    After that, I was still not able to save a location and never saw any errors.
    
    In the Kibana console, the only error message I see is:
  
    ```
    [2022-07-27T15:51:30.870+01:00][ERROR][savedobjects-service.repository.point-in-time-finder] Failed to open PIT for types [tag]
    ```

    
## Feedback

**Step 5**: It's not immediately obvious what the user should do because there are two primary buttons. Should they click the one on the bottom or the one on the top? This is confusing IMO.
**Step 6**: The save button should be capitalized IMO.
**Step 6/7**: The flyout is not closed if I click out of it in the stage with the form for a private location. Instead, it goes to the previous state. IMO it should close completely when clicking outside of it. [See this video to understand.](https://user-images.githubusercontent.com/6868147/181279459-24c6d678-dbc9-444d-8a64-d37aa944b1b9.mov)

**Comment by dominiqueclarke** [comment]
@lucasfcosta Please see https://github.com/elastic/kibana/pull/137526 for the fix to the critical issue. It isn't related to the issue with the beta status label at all, though I will ping you seperately about that

> Feedback
Step 5: It's not immediately obvious what the user should do because there are two primary buttons. Should they click the one on the bottom or the one on the top? This is confusing IMO.

cc: @hbharding for final decision

> Step 6: The save button should be capitalized IMO.

Done

> Step 6/7: The flyout is not closed if I click out of it in the stage with the form for a private location. Instead, it goes to the previous state. IMO it should close completely when clicking outside of it. [See this video to understand.](https://user-images.githubusercontent.com/6868147/181279459-24c6d678-dbc9-444d-8a64-d37aa944b1b9.mov)

I haven't addressed this as of yet. @hbharding what do you think?

**Comment by emilioalvap** [comment]
@dominiqueclarke I'm in the process of running on-prem checks, just wanted to make sure, fleet user should not have permission to enable Monitor Management right? There's a explanatory note for uptime user but nor for fleet, so I'm not sure what the expectation is here.

(Ignore this comment, it's the same @lucasfcosta posted above) ~~A minor thing, if the user selects `cancel` or close the flyout when creating a private location, it always redirects to private locations flyout:~~
[rec](https://user-images.githubusercontent.com/95703246/182156527-d6340cb2-266b-4e4d-8c3e-4b305f627427.gif)

**Comment by emilioalvap** [comment]
@dominiqueclarke qq about lightweight checks. I've noticed `ICMP` and `TCP` checks are displaying `Fleet managed` as locations in the result page, is this intended?

[HTTP](https://user-images.githubusercontent.com/95703246/182161496-0e99af3f-2e45-4cb1-b8f5-2b97a1892d69.png)
vs.
[ICMP](https://user-images.githubusercontent.com/95703246/182161604-6e229060-7539-4969-ae2d-89c1688e0ba2.png)

**Comment by emilioalvap** [comment]
About these two:

<html>
<body>


When | I have a monitor configured for a private location | I cannot delete that private location until all monitors for that location are removed |  
-- | -- | -- | --
When | I have no monitors for a given location | I can delete that private location


</body>
</html>

Found a race condition where if Kibana takes long to respond, it's actually possible to remove a private location with monitors configured. They appear as `undefined` after [that](https://user-images.githubusercontent.com/95703246/182163959-8bba789e-3754-4b97-a508-054fa6b61238.png)


Here's the [recording](https://user-images.githubusercontent.com/95703246/182164543-3d7612b4-2a99-496b-bb38-2ca833e3890f.gif)

**Comment by dominiqueclarke** [comment]
> @dominiqueclarke qq about lightweight checks. I've noticed `ICMP` and `TCP` checks are displaying `Fleet managed` as locations in the result page, is this intended?
> 
> [HTTP](https://user-images.githubusercontent.com/95703246/182161496-0e99af3f-2e45-4cb1-b8f5-2b97a1892d69.png) vs. [ICMP](https://user-images.githubusercontent.com/95703246/182161604-6e229060-7539-4969-ae2d-89c1688e0ba2.png)

@emilioalvap That is not intended. Good catch! Please pull down the fix from this PR and retest. Testing instructions included https://github.com/elastic/integrations/pull/3925

**Comment by lucasfcosta** [comment]
Thanks for the updates @dominiqueclarke! I've just tried adding a location and then a monitor and it's now working for me!

# Fleet user on Cloud context

Images:
* [Location added](https://user-images.githubusercontent.com/6868147/182367681-5b774ca5-cfe3-4bc4-b7d4-e6ee8bd9ddd3.png)
* [Selecting the desired location when creation a monitor](https://user-images.githubusercontent.com/6868147/182367606-6a904bc8-4103-4fdb-a0b2-e1c31f38658d.png)
* [Monitor results](https://user-images.githubusercontent.com/6868147/182367838-2dae0175-c169-4cba-87fc-533662b27a49.png)
* [Edit disabled when there's a monitor](https://user-images.githubusercontent.com/6868147/182368131-77a03cfc-680a-4b62-a6b3-9e7e21efafee.png)
* [I can delete the location just fine after deleting its monitor](https://user-images.githubusercontent.com/6868147/182369947-a6d3f13c-e216-44ff-8b38-b6f7184cd05e.png)
* [I can create two monitors with the same name on different namespaces](https://user-images.githubusercontent.com/6868147/182371499-359858f7-fc2d-494e-a425-ccc85430ce39.png)

## Questions

* [Should the "run once" be disabled if I only selected the private location?](https://user-images.githubusercontent.com/6868147/182367723-2b57203f-35c8-4d1f-bd41-d612b054211e.png)
* [This field is disabled when editing the policy, but it doesn't _look_ disabled. Is this expected?](https://user-images.githubusercontent.com/6868147/182370610-20742c91-16b6-4486-a279-cafe1427309a.png)
* The button to edit the integration in uptime actually brings users to the _list_ of monitors not to that particular monitor's edit page, is that expected? If possible it would be cool to point to the exact monitor edit page.
* You mentioned deleting a policy would make a location invalid, but I couldn't find any way of deleting the policy. How should I do that? I also tried with the superuser and couldn't find any way of doing so. It does seem like the docs for that are out of date: https://www.elastic.co/guide/en/fleet/master/edit-or-delete-integration-policy.html. [See image.](https://user-images.githubusercontent.com/6868147/182374783-aac1901d-e8d3-44a2-9a6b-794d552337cb.png)


# Uptime user on Cloud context

Images:
* [Editing monitors on private locations isn't possible](https://user-images.githubusercontent.com/6868147/182375580-6849cad6-560d-4975-ba99-1b42c23626eb.png))
* [Private locations are disabled](https://user-images.githubusercontent.com/6868147/182378581-aeb068ef-2492-45c7-9833-38bdd0ea45b8.png)
* [I was actually able to generate an API key, but I do see the warning. Can we disable the generation if the user doesn't have permissions to do what they must instead of having the warning? If not, can we highlight the warning somehow?](https://user-images.githubusercontent.com/6868147/182385681-76f0af20-9c5f-4e27-88ab-e9bb917d429f.png)


-------------------

# On prem test is in progress, just thought I'd post this first to accelerate feedback.

**Comment by dominiqueclarke** [comment]
> [Should the "run once" be disabled if I only selected the private location?](https://user-images.githubusercontent.com/6868147/182367723-2b57203f-35c8-4d1f-bd41-d612b054211e.png)

Yes, we do not currently support run once for private locations

> [This field is disabled when editing the policy, but it doesn't look disabled. Is this expected?](https://user-images.githubusercontent.com/6868147/182370610-20742c91-16b6-4486-a279-cafe1427309a.png)

Unfortunately, this is where we are at for MVP. We don't have as much control over those two fields, as they are controlled by the Fleet UI codebase. In the future, we can make improvements, but for MVP we ran out of time to improve this through contributions on the Fleet side.

> The button to edit the integration in uptime actually brings users to the list of monitors not to that particular monitor's edit page, is that expected? If possible it would be cool to point to the exact monitor edit page.

I agree. This has been discussed, and again came down to running out of time. Might be able to get it in as a bug fix, but this change wasn't prioritized. 

> You mentioned deleting a policy would make a location invalid, but I couldn't find any way of deleting the policy. How should I do that? I also tried with the superuser and couldn't find any way of doing so. It does seem like the docs for that are out of date: https://www.elastic.co/guide/en/fleet/master/edit-or-delete-integration-policy.html. [See image.](https://user-images.githubusercontent.com/6868147/182374783-aac1901d-e8d3-44a2-9a6b-794d552337cb.png)

On the agent policy page on the Settings tab, there should be a Delete button at the bottom. You may need to unenroll the agent attached to the policy first. 
<img width="359" alt="Screen Shot 2022-08-02 at 10 10 53 AM" src="https://user-images.githubusercontent.com/11356435/182395855-9beab3b8-40b5-4dd4-b9b2-e427d5daa1df.png">
<img width="360" alt="Screen Shot 2022-08-02 at 10 10 44 AM" src="https://user-images.githubusercontent.com/11356435/182395856-95ce3c03-c121-4a94-8f50-6b4e72ecffb7.png">

> [I was actually able to generate an API key, but I do see the warning. Can we disable the generation if the user doesn't have permissions to do what they must instead of having the warning? If not, can we highlight the warning somehow?](https://user-images.githubusercontent.com/6868147/182385681-76f0af20-9c5f-4e27-88ab-e9bb917d429f.png)

@lucasfcosta , we don't want to disable generation, particularly on cloud, because we don't know if the user intends to use private locations or not. Highlighting the warning better is a good idea. @hbharding thoughts? Disabling it entirely when the user does not have fleet permissions on-prem would make sense. 

When the user doesn't have the proper permissions for UI monitors with private locations, they aren't able to add them at all from the UI. However, with project monitors, if the user tries to create a project monitor with a private location via push with a limited permission API key, they will receive a helpful error message reported back in the CLI.

**Comment by lucasfcosta** [comment]
# On Prem Feedback

## Fleet user

1. [Add monitor button is disabled as expected with the prompt for new location](https://user-images.githubusercontent.com/6868147/182404089-608eddf1-073d-4ced-bfbc-c197349fabad.png)
2. [I can save a new location just fine](https://user-images.githubusercontent.com/6868147/182405048-f3c7f6f6-c7e6-4dbd-8e4e-f1b438fd1339.png)
3. [I can create a monitor just fine](https://user-images.githubusercontent.com/6868147/182405549-ad5fff65-9c55-4990-92a4-5976861d0f08.png)
4. [I can see a monitor's private location when creating it](https://user-images.githubusercontent.com/6868147/182405736-60c3ebda-f288-4a3d-8a43-4d79232c332d.png)
5. [Monitor results appear](https://user-images.githubusercontent.com/6868147/182405670-75319481-2a02-4822-a773-6e98f454da25.png)
6. [I can only delete a priv. location after deleting its monitor.](https://user-images.githubusercontent.com/6868147/182406165-489ef541-8f57-4a7a-977e-061c45f904d8.png)
7. [Not being able to delete an existing policy](https://user-images.githubusercontent.com/6868147/182407457-b153b53c-21c9-4b03-894c-9e4b195791a1.png)
8. [Can't edit the policy either](https://user-images.githubusercontent.com/6868147/182408722-4044cb37-c3f2-43b8-9fc4-b368471f69ce.png)
9. [Deleting the policy makes the location non-deletable and shows the correct message](https://user-images.githubusercontent.com/6868147/182409199-07f137b1-cc37-4c45-b584-588e29eb2c13.png)

# Uptime on Prem

1. [Disclaimer on API key appears](https://user-images.githubusercontent.com/6868147/182409753-94a9f841-2f21-4b95-b35e-ebb49d6ea8e9.png)
2. [Disclaimer and disabled actions on the private locations flyout](https://user-images.githubusercontent.com/6868147/182409908-dc7638df-d954-4706-8e5d-f69fad031865.png)

## Questions

* [I do see the add monitor button enabled and can use it (although edit and delete are correctly disabled)](https://user-images.githubusercontent.com/6868147/182410050-37a7a853-b79b-4cd0-a538-a19f99c0ef9f.png). I thought it should've been disabled?

**Comment by lucasfcosta** [comment]
# Project monitors

## On cloud with fleet

1. [I was able to push a project monitor succesfully to my private location.](https://user-images.githubusercontent.com/6868147/182419152-ae5e97e9-c99f-45ed-9f27-07c93b7a5725.png) [Here's the pushed monitor.](https://user-images.githubusercontent.com/6868147/182419024-8e74cb29-0d4f-4a41-94d1-57a12f04726e.png)
2. [I can see my monitor's results](https://user-images.githubusercontent.com/6868147/182418916-d9d78dbe-a8bb-499f-bd8c-b19e981216fc.png)
3. [I can re-push a monitor using the `--privateLocation` flag and it works.](https://user-images.githubusercontent.com/6868147/182419588-388fd102-d7a0-432d-9907-f2e4a1ac3bcd.png)
4. [The monitor that was not re-pushed is not there anymore](https://user-images.githubusercontent.com/6868147/182419780-ecf46bd8-a7ec-4c48-acf1-58064c6e6691.png) (the old integration policy also disappeared)

## On cloud with uptime user

1. [I get the appropriate error when using the uptime user's keys no matter what I do](https://user-images.githubusercontent.com/6868147/182420702-5781dda0-5d4b-44c7-92df-7b509328b9e4.png)

**Comment by dominiqueclarke** [comment]
> [I do see the add monitor button enabled and can use it (although edit and delete are correctly disabled)](https://user-images.githubusercontent.com/6868147/182410050-37a7a853-b79b-4cd0-a538-a19f99c0ef9f.png). I thought it should've been disabled?

@lucasfcosta I'm assuming this is for an Uptime only user. Did you remove this key in your Kibana.yml file? `xpack.cloud.id: something`

**Comment by lucasfcosta** [comment]
@dominiqueclarke that was it, thank you! Removing it did disable the button. Everything else seems fine still. Thank you very much!

**Comment by lucasfcosta** [comment]
Closing this one and actually moving straight to "Done Done" as recommended by @shahzad31 on Slack.
