### ISSUE TITLE
ML Detection of Duration Anomalies

### ISSUE THREAD

**Issue by andrewvc** [elastic/uptime#71]
This issue is to track adding ML support to our duration charts on the monitor details page. This is a great way to start integrating ML into uptime. We'd like to start showing:

1. The baseline average duration
2. Highlight spikes and drops in response times as anomalous. We should consider these warnings not errors for this initial MVP.

**Open questions:**

Do we show these as warnings or info? Visually, do we communicate this with a yellow or more neutral color?

**Implementation Notes**
Check with APM & SIEM ML integrations on how they:
* Check for License, recommend Trial if not already Trial or Platinum
* Check for resources to run ML
* Enable ML (with set of ML jobs)
* Provide error messages if too much is asked
* Stop ML (and delete ML Jobs)

@katrin-freihofner this might be good to add to our mocks for our redesigned monitor details page.

**Comment by grabowskit** [comment]
Sample of SIEM/ML UI integration...
<img width="1286" alt="Screenshot 2019-08-08 14 01 51" src="https://user-images.githubusercontent.com/28265798/62730617-f45e9780-b9e5-11e9-964b-d0e406a54ee7.png">
Sample of APM/ML UI integration...
<img width="475" alt="Screenshot 2019-08-08 14 06 37" src="https://user-images.githubusercontent.com/28265798/62730688-1e17be80-b9e6-11e9-93c9-c0d37954929e.png">

**Comment by grabowskit** [comment]
Example of APM chart with integrated ML results...

![image](https://user-images.githubusercontent.com/28265798/62731360-929f2d00-b9e7-11e9-8a98-5394ef650b46.png)

**Comment by katrin-freihofner** [comment]
We have something very similar for the logs UI planned:

<img width="1350" alt="Screenshot 2019-10-08 at 16 20 17" src="https://user-images.githubusercontent.com/20965076/66403816-89324100-e9e7-11e9-92a4-eb3071e49075.png">

I think this could work for uptime too.

**Comment by katrin-freihofner** [comment]
This is how it could turn out for the duration chart:

<img width="684" alt="Screenshot 2019-10-08 at 16 37 17" src="https://user-images.githubusercontent.com/20965076/66405218-16769500-e9ea-11e9-9422-82a9548963fe.png">

**Comment by Titch990** [comment]
@katrin-freihofner I just want to say that all these look great!

**Comment by Titch990** [comment]
I also have a couple of comments about the UI text in some of the earlier screenshots above. I'm not sure how far down the line these changes are, and hence whether it is appropriate to comment yet. Also, I wonder who is a good person to raise these points with initially? @gchaps perhaps?

Point 1: I think the text in both the SEIM **Anomaly detection settings** dialog, and the APM **Enable anomaly detection** dialog could be tightened up a bit. I'm happy to help with this.

Point 2: I'm a bit concerned about the use of the word "Integrations" in the APM/ML UI integration. I may be worrying needlessly, and perhaps the term has already been agreed, but I'd we also already have a different kind of "Integration" in Observability. This other "Integration" will appear in the UI and documentation shortly and may cause confusion. 

This other integration is an integration with a third party service, for example, GCP, Docker, MySQL etc. It refers to the mechanism by which we set up (or integrate with) a new data source to deliver logs and metrics data. This usage of "integration" seems to be fairly standard across many third party vendors, not just us.

So in the "Sample of APM/ML UI integration" screenshot above, it's possible that the user may expect the other kind of Observability "integration" rather than what I think is an integration with our machine learning app. I think "Integration" is a very generic term, so perhaps it may be better to choose a more specific term that focuses on what kind of integration this is, or what problem the integration solves for the user, for example "ML integrations" or "Anomaly detection". I think in the Logs app, the Machine learning integration is on a tab called "Analysis", so perhaps that's something else to consider and use consistently across the Observability apps?

**Comment by drewpost** [comment]
> This is how it could turn out for the duration chart:
> 
> <img alt="Screenshot 2019-10-08 at 16 37 17" width="684" src="https://user-images.githubusercontent.com/20965076/66405218-16769500-e9ea-11e9-9422-82a9548963fe.png">

@katrin-freihofner In this example with multiple series, how would the user know which series that anomaly highlighting pertains to?

**Comment by katrin-freihofner** [comment]
@drewpost like discussed, these (red and yellow) indicators are suggesting that there is an anomaly. Similar to the Logs UI, there needs to be a tooltip and a button to drill-down to the ML view for further details.

**Comment by katrin-freihofner** [comment]
Loom walk-through https://www.loom.com/share/963531dee13e472796ad51768c8c718a

**Comment by katrin-freihofner** [comment]
[Design issue](https://github.com/elastic/uptime/issues/155)
